# Generated by Django 5.1.2 on 2024-12-31 19:38

import public.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to='services\\thumbnails', validators=[public.validators.validate_icon_file_extension]),
        ),
    ]
