# Generated by Django 5.1.2 on 2024-11-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="name",
            new_name="your_name",
        ),
    ]
