# Generated by Django 5.1.2 on 2024-12-31 19:38

import public.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_rename_name_contactmessage_your_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.FileField(upload_to='public\\social_links', validators=[public.validators.validate_icon_file_extension]),
        ),
    ]
