# Generated by Django 5.1.2 on 2024-10-18 19:41

import django.db.models.deletion
import public.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreviewType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        upload_to="portfolio/preview_types",
                        validators=[public.validators.validate_icon_file_extension],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.FileField(
                        upload_to="portfolio/technologies",
                        validators=[public.validators.validate_icon_file_extension],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend Tools"),
                            ("backend", "Backend Tools"),
                            ("fullstack", "Fullstack Frameworks"),
                            ("mobile", "Mobile Frameworks"),
                            ("crossplatform", "Crossplatform Frameworks"),
                            ("database", "Databases"),
                            ("data_engineering", "Data Engineering Tools"),
                            ("devops", "Dev Ops Tools"),
                            ("language", "Languages"),
                            (
                                "content_management_systems",
                                "Content Management Systems",
                            ),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "technologies",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="portfolio/projects")),
                ("preview_url", models.URLField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "preview_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="portfolio.previewtype",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(blank=True, to="portfolio.technology"),
                ),
            ],
        ),
    ]
