# Generated by Django 5.1.2 on 2024-12-31 19:38

import public.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewtype',
            name='icon',
            field=models.FileField(upload_to='portfolio\\preview_types', validators=[public.validators.validate_icon_file_extension]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio\\projects'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.FileField(upload_to='portfolio\\technologies', validators=[public.validators.validate_icon_file_extension]),
        ),
    ]
